var defaultHost = "https://www.unrealengine.com";
var stagingHost = "https://unrealengine-gamedev.ol.epicgames.net";
var trackingURL = "https://tracking.unrealengine.com/tracking.js";
var recommendationsTitle = "Other pages you may find useful";
var recommendationsNoResults = "The recommendations system is designed to help you discover information you may find helpful along your development journey. It will take a little time to generate relevant suggestions. Check again later to see what we come up with.";
var recommendationsCookieMessage = "<strong>Note:</strong> Recommendations rely on cookies being enabled in your browser. If you want suggestions of pages you may find useful, make sure to enable cookies.";
var finishButtonTemplate = '<a class="btn btn-default btn-lg finish-step"><span class="glyphicon glyphicon-ok"></span>Finished Step</a>';
var lastVisitedTitle = "Pick up where you left off";
var inboxTitle = "My Docs";
var inboxOptIn = "My Docs provides suggestions to help you discover information you may find helpful based on your history. We need to store some info about the pages you view using cookies in order to make relevant suggestions. Would you like to enable My Docs?";
var inboxAccept = "Enable";